version: '3.8'

services:
  bot:
    build: .
    container_name: booking_bot
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./database:/app/database
      - ./config:/app/config
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - HEADLESS_MODE=true
      - SELENIUM_TIMEOUT=30
      - TZ=Europe/Moscow
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data: 